# Generated by Django 5.0.2 on 2024-02-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
            ],
        ),
    ]
